site_name: Superinsight Documentation 
site_url: https://docs.superinsight.ai
theme:
  name: material
  logo: assets/images/superinsight/logo_white.png
  palette:
    primary: red
nav:
    - What is Superinsight : index.md
    - Quickstart: quickstart.md
    - FAQ: faq.md
    - Setup: 
      - ML Database: setup/database.md
      - ML Table: setup/table.md
    - Operations:
      - Guide: operations/index.md
      - Create: operations/create.md
      - Delete: operations/delete.md
      - Drop: operations/drop.md
      - Federated Query: operations/federated.md
      - Insert: operations/insert.md
      - Search: operations/search.md
      - Predict: operations/predict.md
      - Train: operations/train.md
      - Update: operations/update.md
    - Official Website: https://www.superinsight.ai
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - tables
plugins:
  - i18n:
      default_language: en
      languages:
        en:
          name: English
          build: true
        zh_CN:
          name: 中文 (中国)
          build: true
        zh_TW:
          name: 中文 (台灣)
          build: true
extra:
  generator: false